version: '3.1'

services: 
   postgres-db:
      image: postgres
      ports:
         - target: 5432
           published: 5432
      environment:
         POSTGRES_USER: root
         POSTGRES_PASSWORD: password
         POSTGRES_DB: jobdb
         
         